name: Test devenv

on:
  push:
  schedule:
    - cron: "0 14 * * 1"

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: Checkout devenv repository
        uses: actions/checkout@v3

      - name: Checkout agent repository
        uses: actions/checkout@v3
        with:
          repository: DataDog/datadog-agent
          path: dd/datadog-agent
          fetch-depth: 0

      - name: Create dd link
        run: |
          ln -s "$GITHUB_WORKSPACE/dd" ~/dd

      - name: Install vagrant plugins
        run: |
          vagrant plugin install vagrant-disksize vagrant-reload

      - name: Create VM
        run: |
          vagrant up

      - name: Run setup script
        run: |
          vagrant ssh -c /vagrant/setup.sh

      - name: Test common invoke tasks 
        run: |
          vagrant ssh -c /vagrant/test_utils/check_setup.sh
          
